apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecomm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: binod132/seller-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              value: "seller_db"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ecomm
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: backend
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: Ymlub2Q=
  username: Ymlub2Q=
  password: Ymlub2Q=